### ISSUE TITLE
Windows 10 19044.1826

### ISSUE THREAD

**Issue by WorldWonderful10** [catzsec/UACBypass#1]
It's working on Windows 10 19044.1826 and undetectable against Defender?

**Comment by catzsec** [comment]
Working on windows10, undetected as of now
https://www.virustotal.com/gui/file-analysis/Y2MyNjQyY2Y3MGEwMTczMWZmMDQ0N2JhZmU5YWY0Y2Q6MTY1ODk0MzYzOA==
